spring.application.name=jarvis

# Configuração do Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=tinyllama
spring.mvc.async.request-timeout=60000

# Configuração do Banco de Dados H2 (Persistência em Arquivo)
spring.datasource.url=jdbc:h2:file:./jarvisdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria as tabelas automaticamente baseado nas classes Java (@Entity)
spring.jpa.hibernate.ddl-auto=update

# Console do H2 (Acesse via localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console