spring.application.name=jarvis

# Config do Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=tinyllama
spring.mvc.async.request-timeout=60000

# config do bd H2
spring.datasource.url=jdbc:h2:file:./jarvisdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria as tabelas baseado nas classes java @Entity
spring.jpa.hibernate.ddl-auto=update

# console do H2 localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console